---
title: "Bees Climate Word_JD"
author: "Jessie Davidson"
format: html
editor: visual
---

# Bees Climate Graphs

### Begin by downloading libraries

```{r echo = FALSE}
library(tidyverse)

library(RColorBrewer)

library(rstudioapi)

library(ggpubr)
```

```{r echo = FALSE}
dir_path <- selectDirectory()
setwd(dir_path)
```

```{r}
bio_climate <- read_csv('~/Downloads/bees_climate/data/processed/california_bioclim.csv', show_col_types = FALSE)
```

```{r}
head(bio_climate)
tail(bio_climate)
glimpse(bio_climate)
```

```{r}
ggplot(data = bio_climate, aes(x= bio3, y =  X_ENDC_CWE_))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)+
  labs (title = "Endemism and Isothermalty", 
  ) + 
  xlab("Isothermality") + 
  ylab("Corrected Weighted Endemism")+
  theme_minimal()+
  scale_colour_brewer(palette = 'Set2')+ stat_cor(aes(label=paste(after_stat(rr.label),after_stat(p.label),sep = "~`,`~")))
```

```{r}
ggplot(data = bio_climate, aes(x= bio3, y =  X_ENDC_RICHNESS_))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)+
  labs(title = "Richness and Isothermalty") + 
  xlab("Isothermality") + 
  ylab("Richness")+
  theme_minimal()+
  scale_colour_brewer(palette = 'Set2')+ stat_cor(aes(label=paste(after_stat(rr.label),after_stat(p.label),sep = "~`,`~")))
```

```{r}
ggplot(data = bio_climate, aes(x= bio4, y =  X_ENDC_CWE_))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)+
  labs (title = "Endemism and Temperature Seasonality", 
  ) + 
  xlab("Temperature") + 
  ylab("Corrected Weighted Endemism")+
  theme_minimal()+
  scale_colour_brewer(palette = 'Set2')+ stat_cor(aes(label=paste(after_stat(rr.label),after_stat(p.label),sep = "~`,`~")))
```

```{r}
ggplot(data = bio_climate, aes(x= bio4, y =  X_ENDC_RICHNESS_))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)+
  labs(title = "Richness and Temperature Seasonality") + 
  xlab("Temperature") + 
  ylab("Richness")+
  theme_minimal()+
  stat_cor(aes(label=paste(after_stat(rr.label),after_stat(p.label),sep = "~`,`~")))
```

```{r}
ggplot(data = bio_climate, aes(x= bio5, y =  X_ENDC_CWE_))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)+
  labs (title = "Endemism and Max Temp of Warmest Month", 
  ) + 
  xlab("Temperature") + 
  ylab("Corrected Weighted Endemism")+
  theme_minimal()+
  scale_colour_brewer(palette = 'Set2')+
  stat_cor(aes(label=paste(after_stat(rr.label),after_stat(p.label),sep = "~`,`~")))
```

```{r}
ggplot(data = bio_climate, aes(x= bio5, y =  X_ENDC_RICHNESS_))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)+
  labs(title = "Richness and Max Temp of Warmest Month") + 
  xlab("Temperature") + 
  ylab("Richness")+
  theme_minimal()+
  stat_cor(aes(label=paste(after_stat(rr.label),after_stat(p.label),sep = "~`,`~")))
```

```{r}
ggplot(data = bio_climate, aes(x= bio6, y =  X_ENDC_CWE_))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)+
  labs (title = "Endemism and Min Temp of Coldest Month", 
  ) + 
  xlab("Temperature") + 
  ylab("Corrected Weighted Endemism")+
  theme_minimal()+
  scale_colour_brewer(palette = 'Set2')+
  stat_cor(aes(label=paste(after_stat(rr.label),after_stat(p.label),sep = "~`,`~")))
```

```{r}
ggplot(data = bio_climate, aes(x= bio6, y =  X_ENDC_RICHNESS_))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)+
  labs(title = "Richness and Min Temp of Coldest Month") + 
  xlab("Temperature") + 
  ylab("Richness")+
  theme_minimal()+
  stat_cor(aes(label=paste(after_stat(rr.label),after_stat(p.label),sep = "~`,`~")))
```

```{r}
ggplot(data = bio_climate, aes(x= bio7, y =  X_ENDC_CWE_))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)+
  labs (title = "Endemism and Temp Annual Range", 
  ) + 
  xlab("Temperature") + 
  ylab("Corrected Weighted Endemism")+
  theme_minimal()+
  scale_colour_brewer(palette = 'Set2')+
  stat_cor(aes(label=paste(after_stat(rr.label),after_stat(p.label),sep = "~`,`~")))
```

```{r}
ggplot(data = bio_climate, aes(x= bio7, y =  X_ENDC_RICHNESS_))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)+
  labs(title = "Richness and Temp Annual Range") + 
  xlab("Temperature") + 
  ylab("Richness")+
  theme_minimal()+
  stat_cor(aes(label=paste(after_stat(rr.label),after_stat(p.label),sep = "~`,`~")))
```

### Multiple Linear Regression

##### Covarience plots:

```{r}
plot( ~  bio_climate$bio1 + bio_climate$bio2 + bio_climate$bio3 +
        bio_climate$bio4 + bio_climate$bio5 + bio_climate$bio6 + 
        bio_climate$bio7 + bio_climate$bio8 + bio_climate$bio9 + 
        bio_climate$bio10 + bio_climate$bio11 + bio_climate$bio12)
```
